### ISSUE TITLE
Shuffle Repeat UI Bug

### ISSUE THREAD

**Issue by dinouse** [Luki120/PerfectSpotify#1]
so i want my disable shuffle repeat in now playing ui and it work!![image](https://user-images.githubusercontent.com/62304158/104897274-2635a500-59b3-11eb-8371-89aa6016ee84.png)

but at context button it gone too. ![image](https://user-images.githubusercontent.com/62304158/104897377-42394680-59b3-11eb-8321-c5fd09f38144.png)
can you make it not to gone? love your tweaks!

iphone 6s 14.0 checkra1n 
latest spotify 8.5.86

**Comment by Luki120** [comment]
Hello yes! I'm sorry for this, I already fixed it and I was planning on updating soon but now Spotify drop a new update and it broke a few things, I still need to fix them, but please join my Discord https://discord.gg/9MXfq8Qqbd so I can give you a deb for now!
