### ISSUE TITLE
not showing lyrics. 

### ISSUE THREAD

**Issue by awakenitsme** [Luki120/PerfectSpotify#4]
ios 14.5, iPhone 7 plus, Spotify 8.6.30. I have enabled the option of lyrics from the tweak, and isn’t working. Maybe it can be for an update of spotify. I use that option a lot, hope that can fix this. ^^

**Comment by Luki120** [comment]
The lyrics option doesn't provide native lyrics. That's exactly the reason why in the preferences there's a link called "Can I Use Native Lyrics?", to avoid this types of questions. Read it, and if you can't use another tweak. Lyrication, Lyricify, etc. The option what it does is to unlock lyrics for songs that are very new, just dropped and don't have lyrics yet.
